### PR TITLE
Chatrender Patch

### LINKED ISSUE #484: Arabic not rendering correctly
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

Some or all Arabic may not be rendering correctly. 1.50.7 also has the problem but as far as I can tell 1.50.6 does not

Source
image

1.50.7 - Master
image

1.50.6
image

### LINKED ISSUE #486: Banning words / emote only chat
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Would be great if we could ban certain words so they wont appear on chat or whole massage that contains them will be entirely skipped. Option to make chat emote only :)

### PR DESCRIPTION
**Pull request by ScrubN**
## Fixes

- Fix emojis having padding only on the right
- Fix block art rendering - Will now always render correctly when width >= font size * 29.11 (350@12pt/700@24pt)
- Disable padding on nonFont char rendering so they don't look monospaced
- Fix RTL measure always returning 0.0
- Add note to READMEs about missing fonts in Linux Alpine
- Fix #484 - Long story short don't draw nonFont chars individually
- Fix ChatRenderer blocking the main thread
- Fix `GetFallbackFont()` returning null Typefaces
- Replace remaining WebExceptions
- Reuse already drawn comments from the previous frame - up to 2x faster render speeds for inFont and 7x faster for nonFont!!
- Fix several more render edge cases
- Add banned word list - Close #486 

## Notes

We should honestly move `GenerateCommentSection()` and its sub-methods into the `CommentSection` class. Would make more sense that way and be much easier to handle

### Before:
computed

image

image

### After:
computed

image

image

Source for last image: The rendered white square is probably a modifier?
image

### CODE REVIEW

**Comment by lay295** [comment]
As part of this would you want make the change to not crash if we cannot match a font to a character in GetFallbackFont when fontManager.MatchCharacter() returns null? Maybe just return the message font and log a very obnoxious message for the console? User might notice it because I would think it would then render □ or something similar.

https://github.com/lay295/TwitchDownloader/blob/e87319ad47288541643409fb666855469117c12c/TwitchDownloaderCore/ChatRenderer.cs#L1024-L1032

Just never really considered it before because I always test on Windows and I guess there are a lot of preinstalled fonts so I've never failed to find a fallback for a character.

**Comment by ScrubN** [comment]
That's smart, I don't know why I didn't think of that

**Comment by ScrubN** [comment]
> As part of this would you want make the change to not crash if we cannot match a font to a character in GetFallbackFont when fontManager.MatchCharacter() returns null? Maybe just return the message font and log a very obnoxious message for the console? User might notice it because I would think it would then render □ or something similar.
> 
> https://github.com/lay295/TwitchDownloader/blob/e87319ad47288541643409fb666855469117c12c/TwitchDownloaderCore/ChatRenderer.cs#L1024-L1032
> 
> Just never really considered it before because I always test on Windows and I guess there are a lot of preinstalled fonts so I've never failed to find a fallback for a character.

image

On windows and apparently got a null typeface when rendering a different test json. This was very a good suggestion.

**Comment by ScrubN** [comment]
Now that we draw each comment once we can actually switch to streaming them from the chat json to save on even more memory while rendering. For now though I think I will start setting comments as null when we're done with them

**Pull request merged**
