### PR TITLE
Noto Color Emoji Migration

### PR DESCRIPTION
**Pull request by sunkhaskasis**
This is my attempt at migrating Twitch Downloader from Twemoji to Google Noto Color Emoji. I tried my best to do it, but of course there are certain things I couldn't fix.

Here are some tests with emoji I did, shamelessly stolen from https://getemoji.com/.

<details>
  <summary>Normal Emoji</summary>

 smileys and gestures
food and sport
travel and objects
flags and symbols
</details>

<details>
  <summary>Skin Tones</summary>

image
</details>

And now, for the notes and bugs:

- Right now at least, Noto is bulkier than Twemoji by ~8 MB. I've trimmed as much as I could, leaving only 72x72 images. If you could strip it down a bit more, that'd be great.
- Emoji 14 emoji don't render, for some reason. Maybe it has something to do with the regex string, but the archive does contain images needed for them.
- On their own, hair components and skin modifiers (🏻🏼🏽🏾🏿🦰🦱🦲🦳) don't render. The images for them do exist, however.
- Numbers (0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟) render as partially broken.
- Emoji that are supposed to include the `FE0F` character sometimes render with an extra empty character near them (this is just my hypothesis, I don't actually know what's causing it).

Here is the JSON file I've used to test the emoji. It's rather messy since I just took the order from getemoji, but it should contain everything, including Emoji 14 emoji + hair components and skin modifiers on their own.
https://www.dropbox.com/s/w9tugy84ydlbpoc/emojitest.json?dl=1

I'll also include an empty comment JSON, just so that you could test individual emoji on your own without having to render everything.
https://www.dropbox.com/s/v820dshjohb2zyc/emojitest_blank.json?dl=1

### CODE REVIEW

**Comment by ScrubN** [comment]
> Emoji that are supposed to include the `FE0F` character sometimes render with an extra empty character near them (this is just my hypothesis, I don't actually know what's causing it).

That was indeed the issue for some, though there are more than one variation character that also exhibit the behavior.

> Emoji 14 emoji don't render, for some reason. Maybe it has something to do with the regex string, but the archive does contain images needed for them.

This is also the case for twemoji. Once again the issue is probably an artifact of `Span<T>.StartsWith()` not being the same as `String.StartsWith()` for emojis. I'll try reverting back to strings and see if anything changes, it's probably worth the increased memory usage to users.

> Numbers (0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟) render as partially broken.

They render just fine with Twemoji, probably means that the filename isn't the same in Noto Color?

**Review by ScrubN — CHANGES_REQUESTED** [review]
The README needs to be updated to say *Noto Color Emojis* instead of *Twemoji*

**Comment by sunkhaskasis** [comment]
> They render just fine with Twemoji, probably means that the filename isn't the same in Noto Color?

Yeah, you're right. Here's how they're named in Twemoji:
image

And here's Noto (and it appears there's actually two different sets):
image

**Comment by ScrubN** [comment]
I think you're gonna love this.

1.51.1:
image
image

Using a proper fix:
image
image

Yes there are a few issues here and there left to tackle but its MUCH better.

**Comment by ScrubN** [comment]
> Emoji 14 emoji don't render, for some reason. Maybe it has something to do with the regex string, but the archive does contain images needed for them.

The issue seems to be that `NeoSmart.Unicode` does not contain a definition for emojis above Unicode 13.0

**Comment by sunkhaskasis** [comment]
> > Emoji 14 emoji don't render, for some reason. Maybe it has something to do with the regex string, but the archive does contain images needed for them.
> 
> The issue seems to be that `NeoSmart.Unicode` does not contain a definition for emojis above Unicode 13.0

I made a draft PR in their repo today where I attempt to update it to use emoji from Unicode 14.0. Hopefully, the maintainers will be able to check it out.

https://github.com/neosmart/unicode.net/pull/22

**Comment by sunkhaskasis** [comment]
> I managed to fix the broken skin tones on some specific emojis image image
> 
> However some flags have stopped working correctly and I'm not even remotely sure why. The English, Scottish, and Wales flags have very different sequence encodings and yet `emojiString.StartsWith(emoji.Sequence.AsString)` seems to mix them up. Clearly at some point they did work but I have no clue what I did differently that worked, and also basically every other compound emoji is broken in that render. image image
> 
> I think I'll settle for this right now as its the least broken :p

Have you tested the skin and hair modifiers ((🏻🏼🏽🏾🏿🦰🦱🦲🦳) on their own? Last time they didn't work for me.

**Comment by ScrubN** [comment]
> Have you tested the skin and hair modifiers (🏻🏼🏽🏾🏿🦰🦱🦲🦳) on their own? Last time they didn't work for me.

image

**Comment by sunkhaskasis** [comment]
I see. BTW, my PR in unicode.net was squashed and merged, though the nuget
package is yet to be deployed. You could try compiling it yourself and test
in your local build.

вс, 26 февр. 2023 г., 7:40 Scrub ***@***.***>:

**Comment by Ashdemai** [comment]
Is this related to my issue https://github.com/lay295/TwitchDownloader/issues/578#issue-1610176245 and why I can't render chat?

**Comment by sunkhaskasis** [comment]
> Is this related to my issue [#578 (comment)](https://github.com/lay295/TwitchDownloader/issues/578#issue-1610176245) and why I can't render chat?

No, this PR hasn't even been merged yet. Your issue is something different.

**Comment by ScrubN** [comment]
I just made some improvements to emoji fetching so you'll have to sort that out, sorry.

I was also thinking maybe we could make the emoji type customizable during the migration. That would mean making a separate function for Noto and then can just do an inline if inside the renderer fetch function

**Comment by sunkhaskasis** [comment]
> I just made some improvements to emoji fetching so you'll have to sort that out, sorry.

Did it fix those flags?

> I was also thinking maybe we could make the emoji type customizable during the migration. That would mean making a separate function for Noto and then can just do an inline if inside the renderer fetch function

I mean, it's not like this PR is gonna go anywhere until the newer NuGet package of Unicode.net is released, which might take some time.

**Comment by ScrubN** [comment]
> > I just made some improvements to emoji fetching so you'll have to sort that out, sorry.
> 
> Did it fix those flags?

No, just switching from reading everything into memory to streaming directly to the disk, streaming directly to SKBitmap.Decode. I might have an idea to fix those flags but there's no telling if it'll actually work.

**Comment by ScrubN** [comment]
83680e42931db98fa2e20b26e6afbb3519e5bbf1 I managed to fix the emoji flags by using ordinal comparison specifically on flags, it breaks some other emojis, and I also had the brilliant idea to use a parallelized LINQ query which brought emojitest.json from 1.95x to 3.9x on my system.

**Comment by sunkhaskasis** [comment]
> I just made some improvements to emoji fetching so you'll have to sort that out, sorry.
OK, I think I was able to resolve the conflicts. LMK if something is wrong, it's been ages since I've done it.

**Comment by ScrubN** [comment]
I think you accidentally undid everything you changed in `TwitchHelper.cs`. I can help revert that if you'd like

**Comment by sunkhaskasis** [comment]
Yes, please do. I haven't done any major Git things in years now.

**Comment by sunkhaskasis** [comment]
Thanks. I believe it can be merged now. We'll wait for Unicode.net 14 later, as it might take a few more months.

**Comment by ScrubN** [comment]
Pushing that to the PR from my editor was a bit of a pain. The changes I made:
- Adds the ability to switch vendors
- Fixed a bug where emojis would not render on the first run with a fresh cache, which definitely confused me while adding the switching
- Reduced the noto-emoji zip by about 300KB

The noto-emoji zip will result in a near doubling in the size for the CLI which made me think maybe we should stop embedding the emojis inside the binary and instead fetch it from this git repository when it is required. This also means no emojis when rendering offline with a fresh cache, but I personally think it's worth the smaller initial download size. Does anyone else agree or disagree?

**Comment by ScrubN** [comment]
For the hell of it, I tried compressing the emojis zips as `.tar.gz` and got much better results than zip. The only problem is native TAR support is net7+, but upgrading to net7 severely impacted render performance seemingly unpredictably. I guess this can just be planned for the future?

**Comment by ScrubN** [comment]
I'll merge this for now I guess since nobody commented about fetching emojis at runtime. I'll look into `.tar.gz` archives when we upgrade to NET7, and hopefully we can discuss runtime emoji fetching then too.

**Review by ScrubN — APPROVED** [review]

**Comment by ScrubN** [comment]
+23MB for google noto emojis, that hurts. I really want to implementing downloading them at runtime instead.

**Pull request merged**
