### PR TITLE
Fix very long fragmentParts not wrapping in chat render

### LINKED ISSUE #229: Incorrect outlines for RTL languages
I tried 1.40.1 and Arabic text renders as intended, very small issue tho. the outline for the Arabic text is not correct. example: 
image

I can open a new issue for that if you want, but I thought mentioning it here would be better. btw Thank you for supporting Arabic!

_Originally posted by @mohad12211 in https://github.com/lay295/TwitchDownloader/issues/108#issuecomment-927173600_

### LINKED ISSUE #421: Word wrap problems (1.50.6)
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Twitch
image

TwitchDownloader
image

### PR DESCRIPTION
**Pull request by ScrubN**
Fixes #421
Fixed a few memory leaks - i.e. after rendering about ~800 RTL messages, 3GB of memory had leaked
Fixes #229 - fixed most RTL outlines[^1]

[^1]: RTL scripts with adapting characters (like Arabic) do not render outlines properly. This is an issue with SkiaSharp, not us. See code comment for more details

### CODE REVIEW

**Comment by ScrubN** [comment]
Draft for now will I figure out RTL and wait for opinions on adding link separator wrapping

**Comment by ScrubN** [comment]
I've sorted out all the issues and edge cases I can think of with LTR characters.

@HellbringerOnline [also requested](https://github.com/lay295/TwitchDownloader/issues/421#issuecomment-1312516063) that I add wrapping on the last `?` in a render line to aid in URL readability, like how Twitch wraps URLs. Though in 0.01% scenarios it's not completely faithful to Twitch.

**Comment by ScrubN** [comment]
I wonder how I should go about adding RTL support. I believe in arabic script the shape of a character changes depending on what comes after it, meaning word wrap could alter the readability right?

**Comment by mohad12211** [comment]
I hope that I can with RTL (Arabic speaker)
yes that's right, it changes depending on the letter before it and after it.
twitch adds a `ـ` character at the end of the breaking at the top line, and the beginning at the bottom line.
like this: 
image
I'm not sure if that what you mean by word wrapping.
of course twitch will try to split words to their own lines before trying to split the words themselves.
it's very rare tho and I wouldn't really focus on it that much.

**Comment by HellbringerOnline** [comment]
> I've sorted out all the issues and edge cases I can think of with LTR characters.
> 
> @HellbringerOnline [also requested](https://github.com/lay295/TwitchDownloader/issues/421#issuecomment-1312516063) that I add wrapping on the last `?` in a render line to aid in URL readability, like how Twitch wraps URLs. Though in 0.01% scenarios it's not completely faithful to Twitch.

image
Also I see that links also break after the sign -

**Comment by ScrubN** [comment]
> of course twitch will try to split words to their own lines before trying to split the words themselves.

Yes it will stay that way, but in the case that a word needs to be split to multiple lines due to length it can be pretty complicated in select languages. I'm trying to work on those select languages, which are primarily RTL.

Thanks for the help with arabic

**Comment by ScrubN** [comment]
@mohad12211 I think I got RTL working correct minus the Arabic Tatweel, I'll try to add that in a bit. Could you please check for me that I'm doing it right?

**Comment by ScrubN** [comment]
I was able to confirm the RTL is wrapped correctly

**Comment by ScrubN** [comment]
Side note, I don't know if it's possible to fix the render outline on RTL text:

https://github.com/lay295/TwitchDownloader/blob/9d19a158032a95d1e985aa821311630d7382d76d/TwitchDownloaderCore/ChatRenderer.cs#L647-L653

**Comment by ScrubN** [comment]
> Side note, I don't know if it's possible to fix the render outline on RTL text unless we can mirror the path on the local X-axis
> 
> https://github.com/lay295/TwitchDownloader/blob/9d19a158032a95d1e985aa821311630d7382d76d/TwitchDownloaderCore/ChatRenderer.cs#L647-L653

Turns out there's a matrix transform function.

**Comment by ScrubN** [comment]
I was too stuck in tunnel vision. No matrix math needed :)

**Comment by ScrubN** [comment]
I was able to partially fix RTL outlines. For example Hebrew looks perfect, but Arabic's outlines are quite significantly wider than the drawn text.

**Comment by ScrubN** [comment]
I've realized what the issue is now, and it's an issue with SkiaSharp.

`SKPaint.GetTextPath()` prints RTL strings in reverse order, so the easy solution was to just reverse the character order before calling it, but in the case of Arabic that changes how certain characters look, resulting in the wider outlines.

**Comment by mohad12211** [comment]
I compiled your branch and tested a chat render.
you are right, skiasharp is not aware that the text is RTL for some reason, so you you first had to reverse the letters, but that's not enough, each letter has a different shape depending on its position in a word. skia is also not aware of that and its just displaying letters with the wrong shape.

**Comment by ScrubN** [comment]
I took a look at the SkiaSharp source and if I'm understanding it correctly, the issue may be all the way upstream at Skia :/

**Pull request merged**
