### PR TITLE
Chat Updater Rewrite + GUI frontend, QOL changes

### LINKED ISSUE #448: Segmentation Fault on Render
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

I get a segmentation fault when rendering this VOD:
https://www.twitch.tv/videos/1657833950

https://drive.google.com/file/d/1MdDcFnE9zppHVhRT_7nyFdcMZvJ_LXYb/view?usp=sharing

Seems to fail here when I run through the editor:
image

### PR DESCRIPTION
**Pull request by ScrubN**
#### CLI
- Rewrite `PreParseArgs.ConvertFromOldSyntax()` to be more readable and flexible
- Fix StatusInfo reports not fully overwriting the previous status
- Bump some nuget package versions
- Other cleanup

#### Core
- Sealed runmode classes - This improves performance slightly by disabling inheritance
- Move chatupdate functions from CLI to Core
- Fix all embeds being doubled in chatupdate with arg `--embed-missing`
- Fix crash in chatupdate when `embeddedData` property is `null`
- Made chatupdate task oriented
- Add the ability to move chat crops. Existing comments are preserved, and comments that were cropped out are fetched if possible
- Add the ability to convert chat jsons to other formats
- Made comment flooring math less complex by flipping operations (x * 1/y = x/y)
- Add ability to disable retrieving `comments` and `embeddedData` properties from chat jsons to reduce useless memory usage
- Dispose of embed tasks in `ChatRender` after copying to embed lists to further reduce memory usage
- Redirect all mode cache folders to the root parent so they can be reused between modes
- Change `ReportType.Message[Info]` to `ReportType.Status[Info]` for better clarity
- Remove timestamp bool from ChatDownload as `timestamp-format = None` has the same functionality
- Fixes #448
- Move json, html, txt chat operations to dedicated classes
- Fix sample text height being computed every render tick as it is expensive
- Rewrite `SubstringToTextWidth()` to use spans
- Swap out some lists for arrays, swap out some strings for string bulders
- Use foreach instead of LINQ to do emoji check - slightly faster
- Combine some rtl and non-rtl functions
- Only use DrawShapedText() with messages containing RTL characters
- Minor TwitchHelper optimizations
- Bump some nuget package versions
- Other cleanup

#### WPF
- Add GUI frontend for chatupdate
- Made UI more consistent and readable
- Add additional app icon scales - see comments for details
- Bump some nuget package versions
- Other cleanup

#### Other
- Shorten chatupdate file/namespace/class names
- Add Building from source section to regular README
- Add ChatUpdate to CLI README
- Update READMEs to be more accurate and fix typos

### Notes:
- This is a pretty big PR. Sorry for stealing your evening (:

### CODE REVIEW

**Comment by ScrubN** [comment]
I just learned something. With CommandLineParser, nullable bools cannot be assigned when the short char is used. I opted to make embed-missing default false and rather than removing its short char

**Comment by goldbattle** [comment]
I think it would be fine to remove the short char if we need to.

I have not tested this PR, but it is very promising (a much better implementation of trying to update chat information, instead of redownloading).

The problem with updating the comments/ crop is that the vod still needs to be up. I think you are checking for that already. The emotes and badges shouldn't require this check since it only depends on what has already been downloaded.

**Comment by goldbattle** [comment]
Could you explain where this bug was?
> Fix all embeds being doubled with arg --embed-missing

**Comment by ScrubN** [comment]
> Could you explain where this bug was?
> 
> > Fix all embeds being doubled with arg --embed-missing

Using `--embed-missing` as a guard conditional was pretty smart, however I think it somewhat confused you when writing emotes to `chatRoot`. Using `firstparty` as an example, you can see the `embeddedData` is set to a blank list if it is null or `--replace-embeds` was passed, which is good. However in the case `--embed-missing` was passed, the list is left as-is. From there, the script enumerates through every emote from the response list and appends it to `chatroot.embeddedData`, assuming the emote was not already in the list.

```cs
List<TwitchEmote> firstPartyEmoteList = await TwitchHelper.GetEmotes(chatRoot.comments, _updateOptions.TempFolder, chatRoot.embeddedData);

...

if (chatRoot.embeddedData.firstParty == null || updateOptions.ReplaceEmbeds)
{
    chatRoot.embeddedData.firstParty = new List<EmbedEmoteData>();
}
foreach (TwitchEmote emote in firstPartyEmoteList)
{
    EmbedEmoteData newEmote = new EmbedEmoteData();
    newEmote.id = emote.Id;
    newEmote.imageScale = emote.ImageScale;
    newEmote.data = emote.ImageData;
    newEmote.width = emote.Width / emote.ImageScale;
    newEmote.height = emote.Height / emote.ImageScale;
    chatRoot.embeddedData.firstParty.Add(newEmote);
}
```

The easy solution to this is to check the the ids of all the emotes already in the list against the id of the emote about to be appended.

```cs
...
foreach (TwitchEmote emote in firstPartyEmoteList)
{
    if (chatRoot.embeddedData.firstParty.Any(x => x.id.Equals(emote.Id)))
        continue;

    EmbedEmoteData newEmote = new EmbedEmoteData();
...
```

**Comment by ScrubN** [comment]
> I think it would be fine to remove the short char if we need to.

Given that all of the other update options have short chars, I would rather leave the short char and make it default to false for the consistency

> The problem with updating the comments/ crop is that the vod still needs to be up. I think you are checking for that already.

Yep, and I already have checks for that. I swapped out some `throw new Exception()` for `throw new NullReferenceException` in `ChatDownloader` because they are all thrown as the result null response from twitch and thus making them NRE is more descriptive. I also added an NRE check on the video id before anything is done so we don't need to wait for the response to throw for null or blank video ids.

Anyways doing this allowed me to catch for only NREs which also meant in the same block I could safely assume `chatRoot.video.id` (to be added by PR440) is not null. In the case that it IS null the same NRE catch block activates, which would have later been thrown by `ChatDownloader` anyways.

```cs
try
{
    // Only download missing comments if new end crop is greater than old end crop
    if (_updateOptions.CropEndingTime > chatRoot.video.end)
    {
        ChatDownloadOptions downloadOptions = GetCropDownloadOptions(/*chatRoot.video.id,*/null, tempFile, _updateOptions.FileFormat, chatRoot.video.end, _updateOptions.CropEndingTime);
        await AppendCommentSection(downloadOptions, tempFile, cancellationToken);
    }
}
catch (NullReferenceException)
{
    progress.Report(new ProgressReport() { reportType = ReportType.Log, data = "Unable to fetch possible missing comments: source VOD is expired or embedded ID is corrupt" });
}
``

**Comment by ScrubN** [comment]
I love when git inflates my line count and blames me by counting replacing spaces with tabs

**Comment by goldbattle** [comment]
> Using `--embed-missing` as a guard conditional was pretty smart, however I think it somewhat confused you when writing to `chatRoot.embeddedData`. Using `firstparty` as an example, you can see the `embeddedData.firstParty` is set to a blank list if it is null or `--replace-embeds` was passed, which is good. However in the case `--embed-missing` was passed, the list is left as-is. From there, the script enumerates through every emote from the response list and appends it to `chatroot.embeddedData.firstParty`, assuming the emote was not already in the list.


Oh I thought that the functions would internally handle the duplicates by checking if they exists in the passed emote vector:
https://github.com/lay295/TwitchDownloader/blob/bac2dcf71366f275f697ed256d89a6b4e3d6b08c/TwitchDownloaderCore/TwitchHelper.cs#L235

The important functionality, is that the old emotes should *NOT* be replaced with newer version, just ones that are missing should be added (example is holiday emotes).

**Comment by ScrubN** [comment]
> Oh I thought that the functions would internally handle the duplicates by checking if they exists in the passed emote vector:

No, a standard list allows for duplicate entries. You could get around this by using a SortedSet<> and overriding the Comparer functionality to act predictably for your object type but by then you're overcomplicating the solution and doing an 0N2 bubble sort every time you add an object.

By then we may as well use the magic of LINQ to compare values before we even instantiate the new emote object, which the SortedSet<> solution would not be able to do

**Comment by ScrubN** [comment]
I realize that may seem hypocritical given we use a SortedSet<> for handling comment additions, however in that case we are using it to sort the comments by their offsets. That's more what SortedSet<> is for rather than using it to only remove duplicate elements

**Comment by ScrubN** [comment]
I added more sizes to the WPF icon. Here's some pictures showing the difference it makes:
original
new
Having the multiple resolutions is pretty important. Having just the low res obviously means no upscaling and having just the high res leads to really ugly nearest neighbor downscales from Windows. To make them I used GIMP to downscale the uncropped 1024x1024 PNG using NoHalo interpolation, cubic was pretty fuzzy.
layers

**Pull request merged**
