### PR TITLE
Link support

### PR DESCRIPTION
**Pull request by Teknoist**
Maybe work ? I dont know :P

### CODE REVIEW

**Comment by ScrubN** [comment]
No that will not work. I can add link support to the CLI in the near future.

**Comment by ScrubN** [comment]
Yes it seems it does work, though I would rather the calculation be done in [DownloadVideo.cs](https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/Modes/DownloadVideo.cs) to keep the argument files clean. If you can move it there and add link support to clips and chats then that'd be great.

**Comment by Teknoist** [comment]
private void ExtractIdFromUrl() {
    if (!_id.Contains("http")) return;

    Uri uri = new Uri(_id);
    _id = uri.AbsolutePath.Split('/').Last();
}

This should work for extra parameters.

I'll try to look tonight for the other one

**Comment by Teknoist** [comment]
```
private static VideoDownloadOptions GetDownloadOptions(VideoDownloadArgs inputOptions)
{
    // Extract video ID from URL
    string videoId = "";
    int startIndex = inputOptions.Id.LastIndexOf("/") + 1;

    if (startIndex > 0)
    {
        videoId = inputOptions.Id.Substring(startIndex);
    }

    // Validate video ID
    if (string.IsNullOrWhiteSpace(videoId) || !videoId.All(char.IsDigit))
    {
        Console.WriteLine("[ERROR] - Invalid VOD ID, unable to parse. Must be only numbers.");
        Environment.Exit(1);
    }

    inputOptions.Id = videoId;

    VideoDownloadOptions downloadOptions = new()
    {
        DownloadThreads = inputOptions.DownloadThreads,
        Id = int.Parse(inputOptions.Id),
        Oauth = inputOptions.Oauth,
        Filename = inputOptions.OutputFile,
        Quality = inputOptions.Quality,
        CropBeginning = inputOptions.CropBeginningTime > 0.0,
        CropBeginningTime = inputOptions.CropBeginningTime,
        CropEnding = inputOptions.CropEndingTime > 0.0,
        CropEndingTime = inputOptions.CropEndingTime,
        FfmpegPath = string.IsNullOrWhiteSpace(inputOptions.FfmpegPath) ? FfmpegHandler.ffmpegExecutableName : Path.GetFullPath(inputOptions.FfmpegPath),
        TempFolder = inputOptions.TempFolder
    };

    return downloadOptions;
}
```

**Pull request closed without merging**
