### PR TITLE
Chatupdate patch

### PR DESCRIPTION
**Pull request by ScrubN**
- Fix `chatupdate -R`
- Add cancellation token to `ChatRender.ParseJsonAsync()` and `ChatUpdater.ParseJsonAsync()`
- Suppress WebClient warnings[^1]

[^1]: Annoyingly, HttpClient still does not have a replacement for `WebClient.DownloadFileTaskAsync()`. We can get the stream for the HttpClient and intercept it every 8MB to write to the disk, but at 10 download threads that becomes +80MB or more whereas `WebClient.DownloadFileTaskAsync()` doesn't need the 8MB memory buffer.

### CODE REVIEW

**Comment by goldbattle** [comment]
There is a subtle difference between the two options. The `-E` should direct add only new emotes, or badges that are missing from the already downloaded json. This is to update the json archive to include unreachable emotes, or badges that were not embedded at that time.

The `-R` should wipe all embedded emotes and replace with the current set used by the channel. This will, for example, remove embedded historical holiday emotes with the current ones on the channel.

I have not had time to check the re-write to to the chatupdater portion (holidays are busy), but I think both these functionalities are very important. From an archival standpoint, I want to be able to just *append* to the json as needed, without destroying the old historical data (old chat messages and emotes should remain).

**Comment by ScrubN** [comment]
> There is a subtle difference between the two options. The `-E` should direct add only new emotes, or badges that are missing from the already downloaded json. This is to update the json archive to include unreachable emotes, or badges that were not embedded at that time.
> 
> The `-R` should wipe all embedded emotes and replace with the current set used by the channel. This will, for example, remove embedded historical holiday emotes with the current ones on the channel.
> 
> I have not had time to check the re-write to to the chatupdater portion (holidays are busy), but I think both these functionalities are very important. From an archival standpoint, I want to be able to just _append_ to the json as needed, without destroying the old historical data (old chat messages and emotes should remain).

I see what you mean, though achieving that would require another restructure because of the issue being experienced in #472. As it stands in 1.51.1, you will not be getting that functionality anyways because `-R` still passes the old `embeddedData` to the respective `TwitchHelper` function. As mentioned in [\[2\]](https://github.com/lay295/TwitchDownloader/pull/474#user-content-fn-2-1574b6dc53d4477095da9b0f27de30c5), `TwitchHelper.GetBadges()` needs a partial rewrite and then we can add `-R` back but with actual functionality.

**Comment by ScrubN** [comment]
I decided to just comment out -R instead of removing it because that makes re-adding much easier. Before it's re-added though, we need to fix the duplicate badges in `TwitchHelper.GetBadges()`. I took a stab at serializing the badge response but it kept throwing serialization exceptions :p

**Comment by lay295** [comment]
I think https://github.com/lay295/TwitchDownloader/commit/8cb8fb0af26ad7030c939f77e459bd90b6295d5c should address the duplicate badges. Should no longer have duplicate "bits" and if there are channel specific badges that will be stored over the global ones.

**Comment by ScrubN** [comment]
I think you did fix the duplicates. I'll update this branch to fix -R now

**Pull request merged**
