### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by ScrubN**
There were a lot of changes. To TL;DR it, `StartUri` (`App.xaml`) is no longer used, the app is now instanced from `App.xaml.cs`. Added `Properties/ThemeHelper.cs` to handle theme switching. Added logic to individual windows to get immersive dark title bar. Added `Themes` folder to store applicable themes.

The app's theme will adapt to windows when set to `System` or allow for manual theme choosing in the settings page. High contrast is currently not implemented.

Some elements are unable to be completely themed (Checkboxes, RadioButtons, Dropdowns, TabItems) leading to odd (or ugly in the case of TabItems :c ) results

Related issue: #356

### CODE REVIEW

**Comment by ScrubN** [comment]
Don't merge this yet, I forgot to make some small changes

**Comment by ScrubN** [comment]
Ready to be merged!

**Comment by ScrubN** [comment]
Also as an additional note, there is a way to override the default TabItem to be compatible with the dark mode but this was already a lot of work. I might look further into it if I add ever high contrast.

Docs:
https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-create-apply-template
https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/tabcontrol-styles-and-templates

**Comment by lay295** [comment]
Hey, thanks a lot for the PR. Looks amazing and people might finally not have their eyes burned out with the new theme.

The one thing I did change about it was the background on the checkboxes, it changed the behavior of the default theme so I removed it. Before if it was unchecked it stayed white and only when checked it turned the background color. Seemed a bit strange so I removed it and it still looks OK in dark mode.

Might try and mess with some theme stuff on the weekend, but thanks a lot for the dark mode! I'm sure a lot of people will appreciate it.

**Comment by ScrubN** [comment]
Yeah, when I realized changing the checkbox background color would also override the color of while checked, I panicked and decided to just make it an accent color. I should've gone back on that when I discovered also dropdowns couldn't be styled properly.

**Comment by ScrubN** [comment]
Also if you do mess around with the themes, I should probably clarify that the "Inner" keys are currently used for double-stacked elements, similar to Blender's skin naming scheme. 

i.e.
`Stackpanel (AppBackground)
    -> some kind of collapsible panel (AppElementBackground + AppElementBorder)
        -> Button (AppElementInnerBackground + AppElementInnerBorder)`

I'll probably also add a border width key of some kind if and when I touch the high contrast theme.

**Pull request merged**
