### PR TITLE
Fix removed twitch emotes throwing 404 (#396)

### PR DESCRIPTION
**Pull request by ScrubN**
Related issue: #396

### CODE REVIEW

**Comment by ScrubN** [comment]
> > it would just skip over every missing emote.
> 
> Missing emote should maybe have a "missing" emote like a black square or something ? Maybe configurable color ?

Someone requested a graphic for missing emotes. I think it's a pretty decent idea. Unsure if it should be a color square, "missing" text, or a generic missing texture. Also unsure where it would be hosted, lay would you be willing to host it on twitcharchives?

**Comment by ScrubN** [comment]
@lay295 are you waiting for me to mark my own PRs as reviewed?

**Comment by lay295** [comment]
> @lay295 are you waiting for me to mark my own PRs as reviewed?

Just been too busy with work to look at your PRs :'(

**Comment by ScrubN** [comment]
> Just been too busy with work to look at your PRs :'(

Ah, that's fair. Take your time, work comes first

**Pull request merged**
