### PR TITLE
Clarify README

### PR DESCRIPTION
**Pull request by ScrubN**
Updated README; `--embed-emotes` is no longer valid, new syntax is `--embed-emotes=true`

### CODE REVIEW

**Comment by lay295** [comment]
Oh, I didn't intend to change the syntax like that. I'll change the booleans that are defaulted to fault to not change that behavior but keep the nullable booleans for the defaulted true ones.

**Comment by ScrubN** [comment]
In that case I'll modify the README to clarify that

**Comment by ScrubN** [comment]
Didn't know renaming branches closed open PRs lol

**Comment by ScrubN** [comment]
Clarified some wording, fixed incorrect defaults, and added missing defaults to README. Made Options.cs formatting more consistent. Ready to merge.

**Pull request merged**
