### PR TITLE
Update 7TV emote API

### PR DESCRIPTION
**Pull request by sunkhaskasis**
With 7TV deprecating its old API soon, I figured it'd be a good idea to update the emote endpoint.

### CODE REVIEW

**Comment by IS2511** [comment]
@sunkhaskasis this MR has conflicts, resolve maybe?
Moving to the new API URL is a must

**Comment by sunkhaskasis** [comment]
It seems we'll have to wait for Lay to fix it, as his code still uses the old API endpoint.

> @sunkhaskasis this MR has conflicts, resolve maybe? Moving to the new API URL is a must

**Comment by IS2511** [comment]
What do you mean "we'll have to wait", your PR has conflicts:

image

Lay recently made lot's of changes (like 7 hours ago)

**Comment by sunkhaskasis** [comment]
Ah, I see. First time doing this. I believe this should be OK now.

**Comment by sunkhaskasis** [comment]
> Ah, I see. First time doing this. I believe this should be OK now.



> What do you mean "we'll have to wait", your PR has conflicts:
> 
> image
> 
> Lay recently made lot's of changes (like 7 hours ago)

Ah, I see. First time doing this. I believe this should be OK now.

**Comment by sunkhaskasis** [comment]
The endpoints probably should be updated _again_ since 7TV has moved on to v3 of their API.
https://7tv.io/docs

**Pull request merged**
