### PR TITLE
Move video poperty above comment property in chatroot

### LINKED ISSUE #409: Chat JSON Property Order
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Hi, I would very much appreciate if chat files downloaded in the JSON format could have their properties ordered such that the `video` property comes before the `comments` property. As it is currently, the entire `comments` property of the JSON must be parsed and stored in memory before the correct video offset can be retrieved. Placing the `video` property before the `comments` property would allow processing the chat JSON as a stream, in situations where the file might be very large, and take up a lot of memory. Reordering the JSON properties can be done using the [[JsonPropertyOrder]](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertyorderattribute) attribute, which was added in .NET 6. Sample usage of the attribute can be found [here](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-6-0#configure-the-order-of-serialized-properties). The only changes necessary would be to add the `[JsonPropertyOrder]` attribute to the `ChatRoot` class properties in [ChatRoot.cs](https://github.com/lay295/TwitchDownloader/blob/611ae6a7e448709df627af0ef0dad9dfadb11586/TwitchDownloaderCore/TwitchObjects/ChatRoot.cs).

### PR DESCRIPTION
**Pull request by ScrubN**
Fixes #409

### CODE REVIEW

**Comment by ScrubN** [comment]
No compatibility issues. The main change is that `video` comes before `comments`, easier for users to find and could theoretically open the door to some minor performance boosts if chat renderer is ever rewritten

```
{
"streamer": {},
"video": {},
"comments": [],
"emotes": {}
}
```

**Comment by striker4150** [comment]
Maybe emotes could come before comments as well? That way, the emote lookups can be done without parsing the entire comments section.

**Comment by goldbattle** [comment]
I would keep the emotes at the bottom as it is optional to embed them, and
also "parsing" them is not really that possible since there data is encoded
into a giant base64 string encoding.

**Comment by ScrubN** [comment]
I agree with goldbattle, as well as the fact that the embedded emote section is usually tens of times larger than the comment section

**Comment by striker4150** [comment]
A good question to ask is if the JSON data is streamed, would it be better to deserialize the emotes before the comments? If emotes are deserialized first, it would mean that emotes in comments can be looked up immediately as they appear, but if they are deserialized later, the comments must be processed again to handle emotes. Due to this, it seems to me that it would be more efficient to deserialize emotes first, but I don't know whether the pros outweigh the cons, and whether it would affect performance all that much. Anyone want to pitch in?

**Comment by striker4150** [comment]
I think you misunderstood me. I know that the JSON is not streamed. I was considering a hypothetical scenario where the JSON is streamed for performance reasons. I was asking more about the performance of storing emotes vs. comments in memory, and your response answered my question.

**Comment by ScrubN** [comment]
I thought on it a little more. If memory ever becomes an issue, the first move should not straight jumping to streaming the emotes from the json/download cache. The first move should be allocating memory for emote image data as it's needed. Rather than loading every third party emote's image data into memory, there's very likely to be some that aren't used; when was the last time you saw someone use WubTF. Storing only the emote's properties for doing the lookups and then loading image data into ram the first time it is used would cut average emote memory usage significantly.

Of course chat downloads would still have to contain every emote, though it would be good to refactor the json writer to fetch the emotes as they're being written so the program isn't using 600MB+ of ram in a worst case like Mizkif.

Also when looking into this I found a minor bug in the html writer but nobody uses that anyways lol

**Pull request merged**
