### PR TITLE
Chatrender patch again

### LINKED ISSUE #495: Unlisted 7TV emotes
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

In the latest version,  7TV emotes marked as " unlisted emote "  do not work.
In old version 1.40.2 they work.
For exampe this emote:
https://7tv.app/emotes/6287c2ca6d9cd2d1f31b5e7d

### LINKED ISSUE #529: Animated emotes freezing after certain message count
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When rendering chat, even with a partial render of say 1000 messages, if it goes beyond around the 80000 messages point from the json file, all animated emotes will be frozen.

Not to mention rendering a chat with over 80000 at least with prores and importing into premiere pro gives a blank video.

Is anyone else having this issue? The streams I've downloaded these from have been deleted at this point but if it's an issue with the chat download settings it'd be great to know for future reference. Thanks.

### PR DESCRIPTION
**Pull request by ScrubN**
- Fix #495 by allowing unlisted emotes by default with an option to disable
- Fix #529 - Int32 overflow caused animated emotes to break at 19:53:03 (71,583 seconds). We will use long instead.
- Fix banned word list not working correctly in multiple ways
    - Just straight up didn't work half the time
    - Theoretically it would have censored "foobar" if the banned word was "foo"
image
I think the new regex approach is better for catching banned words instead of the blanket `string.Contains()` it used previously.
- Add additional cancellation tokens to some methods
- Query the fallback font cache only once and with CollestionsMarshal allowing for about 1-4% render speed increase with non-font renders.
**NOTE** this change requires moving from `ConcurrentDictionary<int, SKPaint>` to `Dictionary<int, SKPaint>` meaning it is no longer thread-safe, however thead safety isn't exactly a priority at the moment and can be reimplemented with a simple lock.
- Remove redundant expensive operations - `List<string>.ToArray()` only to iterate it with foreach, doing the same LINQ method twice when finding the bit prefix
- Don't copy the frame if there are no animated emotes to draw
- Optimize reversing RTL text to draw the correct outline with `Span<T>.Reverse()` (~6x faster & ~1/6th allocations)
- Fix block art width calculation using untrimmed string
- Skip checking if third party emote/emoji when drawing non-emoji buffer
- Add CLI option to skip drive waiting
- Misc cleanup

### CODE REVIEW

**Comment by ScrubN** [comment]
@lay295 can I have your emoji test chat? I want to test a possible increase to emoji performance.

**Comment by ScrubN** [comment]
At this point, I believe about 70% of render time is spent on SkiaSharp or SkiaSharp.HarfBuzz, with 58% of render time just spent waiting on `SKBitmap.Copy` within `DrawAnimatedEmotes()` or `SKBitmap.get_Bytes()` to send to ffmpeg
image
image

**Comment by ScrubN** [comment]
I believe I just found some more issues with RTL. I honestly have no clue what could be causing this. To add even more confusion, Github/HTML disagrees with how VSCode displays the LTR at the end of the RTL

image
image

`"وعليكم السلام ورحمة الله وبركاته نورت/ي البث smoo111"`

image
image

`"❤هلابك الله يحييك"`

**Comment by mohad12211** [comment]
I good metric for RTL combined with LTR is how discord does it.
github is weird sometimes, and I don't know about vscode

**Comment by ScrubN** [comment]
> At this point, I believe about 70% of render time is spent on SkiaSharp or SkiaSharp.HarfBuzz, with 58% of render time just spent waiting on `SKBitmap.Copy` within `DrawAnimatedEmotes()` or `SKBitmap.get_Bytes()` to send to ffmpeg image image _Note: Profile taken with [34cbafe](https://github.com/lay295/TwitchDownloader/commit/34cbafe26c17fda6701da1626f006ff947375a42), not [335a7d5](https://github.com/lay295/TwitchDownloader/commit/335a7d55d560bcb0400f123ac0d126fcea1a470b)_

I implemented some code to skip copying if there are no animated emotes to draw allowing for up to 10% speedup, not bad. From there I wanted to see what the primary bottleneck is. Sending the frame bytes to a discard `_ = frame.Bytes;` instead of ffmpeg `ffmpegStream.Write(frame.Bytes);` increased render speed from ~45x to ~93x. Furthering that by not grabbing the frame bytes at all increased render speeds to over 620x. The next step in optimization seems to be writing a custom unsafe method for copying the frame bytes to the ffmpeg stream, though SkiaSharp already uses an unsafe method under the hood for `SKBitmap.Bytes` so who knows what we can even do.

Also with no frame copying `DriveHelper.WaitForDrive()` uses ~17% of CPU time so if we can optimize frame copying then maybe the next step is an arg to disable drive waiting since it was implemented to help with crappy USB drives that briefly disconnect under heavy load.

**Comment by ScrubN** [comment]
> I implemented some code to skip copying if there are no animated emotes to draw allowing for up to 10% speedup, not bad. From there I wanted to see what the primary bottleneck is. Sending the frame bytes to a discard `_ = frame.Bytes;` instead of ffmpeg `ffmpegStream.Write(frame.Bytes);` increased render speed from ~45x to ~93x. Furthering that by not grabbing the frame bytes at all increased render speeds to over 620x. The next step in optimization seems to be writing a custom unsafe method for copying the frame bytes to the ffmpeg stream, though SkiaSharp already uses an unsafe method under the hood for `SKBitmap.Bytes` so who knows what we can even do.
> 
> Also with no frame copying `DriveHelper.WaitForDrive()` uses ~17% of CPU time so if we can optimize frame copying then maybe the next step is an arg to disable drive waiting since it was implemented to help with crappy USB drives that briefly disconnect under heavy load.

No matter what I try I cannot find a solution that is both faster and does not somehow implement a memory leak. For example this should theoretically be faster because it allocates nothing to the heap and yet it causes GC to go on vacation allowing memory to skyrocket 4x higher than if we just use `SKBitmap.Bytes`, which re-allocates the bitmap's pixel buffer to a new array.
image
image
How streaming unmanaged memory is both slower and less memory efficient than re-allocating it is beyond me but it seems there just may not be a faster way, which is a huge shame given the amount of render time spent purely on copying.

Perhaps we could have 2 bitmaps and alternate between which one we render to and use a background thread to copy the previous bitmap to ffmpeg so we can continue rendering while copying to ffmpeg? Sounds a bit complicated to achieve though.

**Comment by ScrubN** [comment]
So between 1.51.1 (8c0c996ed3a74804e5d41a7efdb9a8dbcf26fc3a) and master (ab5c5d10a40cd0359adc49783e18a4f71d7a521b) RTL rendering went from ~15-20x -> ~40x but LTR went from ~50-60x -> ~44x (tested across multiple sessions). I'm not entirely sure what's caused it but I don't think it was comment reuse or the drive fix.

image
Top is an arabic chat, bottom is english.

**Comment by ScrubN** [comment]
I honestly can't figure it out. Even publishing the older commits I can't reproduce the 50-60x I've seen with some LTR renders using 1.51.1. Is it maybe caching the JIT's optimizations between runs? I have no clue.

**Comment by ScrubN** [comment]
I've found the source of the render speed drop.
Left is .NET6 right is .NET7. They both have the exact same codebase, they only change is the target framework.
image
Top is .NET6 bottom is .NET7. I have absolutely no clue why the framework upgrade causes the program to run significantly slower while also using less CPU resources.
image
image
image
image
I'm reading around and it seems like they significantly changed the JIT, maybe we got super unlucky? Or maybe the problem is Ffmpeg is somehow being harmed by the framework switch? I have no clue.

**Comment by ScrubN** [comment]
> I believe I just found some more issues with RTL. I honestly have no clue what could be causing this. To add even more confusion, Github/HTML disagrees with how VSCode displays the LTR combined with RTL
> 
> image image
> 
> `"وعليكم السلام ورحمة الله وبركاته نورت/ي البث smoo111"`
> 
> image image
> 
> `"❤هلابك الله يحييك"`

I'm not exactly sure what the cause of either of these is to be completely honest. For now it will just have to remain sadly

**Pull request merged**
