### PR TITLE
Initial GUI Localization Support

### LINKED ISSUE #445: Multi Language Support
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Can we add language support.

### PR DESCRIPTION
**Pull request by ScrubN**
### Breaking Change!
I was having issues getting this working because the WPF project uses both the `TwitchDownloader` and `TwitchDownloaderWPF` namespaces, so I was forced to rename migrate to `TwitchDownloaderWPF`. As a result the application is now named `TwitchDownloaderWPF.exe`, meaning the auto updater will relaunch the wrong application and thus it is recommended that users fully redownload whenever this is released.

I tried using `<AssemblyName>TwitchDownloader</AssemblyName>` to restore the old name but that caused a guaranteed crash when using any language other than English.

<br>
I have created an initial French translation in its own commit (53245be1fe55768d525905e81cc2cd0c12469b03) as a guide for what others need to do to translate the app. Here's hoping the remains of my highschool knowledge + wordreference & deepL makes for a good enough initial translation.

- Closes #445

Co-authored by @Teknoist

### CODE REVIEW

**Comment by ScrubN** [comment]
I think I would like to merge this for 1.51.3 in a few days, and perhaps even call it 1.52.0 because its a pretty big and breaking change. Thoughts @lay295 ?

**Comment by ScrubN** [comment]
TODO: update WPF README again

**Comment by lay295** [comment]
> I think I would like to merge this for 1.51.3 in a few days, and perhaps even bump it to 1.52.0 because its a pretty big and breaking change. What do you think @lay295 ?

Oh just saw this now, go for it :)

**Comment by ScrubN** [comment]
After almost 2 months, it feels good to get this done.

**Pull request merged**
