### PR TITLE
Add 7tv emotes support

### LINKED ISSUE #181: Request to add 7TV, another third party emote service
Add support for [7tv](7tv.app), another third party emote service like BTTV or FFZ.

### PR DESCRIPTION
**Pull request by IS2511**
Closes #181

### CODE REVIEW

**Comment by IS2511** [comment]
Probably needs a bit of testing, I did build it and get a 10 minute fragment of chat rendered with both types of emotes (channel and global), but I heard it crashes on another PC when rendering with alpha bg (generate mask)

I didn't test this thoroughly, might be a mime thing for example. Don't have enough time :(

**Comment by IS2511** [comment]
Ok, found some theoretical bugs, closing for rework (probably tomorrow)

**Comment by lay295** [comment]
Oh cool, haven't had time to look into it but cool someone else did.

The crashing thing is probably not related to the code you've changed. I mentioned the issue [here](https://github.com/lay295/TwitchDownloader/issues/57#issuecomment-677989306) a little but essentially for some reason with generate mask SkiaSharp is throwing a memory access error.

I found by [disabling optimizations](https://github.com/lay295/TwitchDownloader/blob/afcfefa23ee52610ae10ca6c7ba6f45e4b04ef80/TwitchDownloaderCore/ChatRenderer.cs#L449) it would fix it on the specific function. I never really tried to find the root cause of the crash and just put a bandaid solution on.

**Comment by IS2511** [comment]
Why is every emote saved to a `.png`? Gifs save with a `.png` extension too... For compatibility? If it's working as intended I'm reopening the pull request because it probably works ok then

**Comment by IS2511** [comment]
Just in case I will mention it here, 7tv for some reason actually can return jpeg (if the emote was uploaded in jpeg), is this supported in the base code?

**Comment by lay295** [comment]
It's a lot of weirdness and I'm not really proud of a lot of the code in this repo. It was originally just static images getting stitched together and when GIF support was just an afterthought so when it was added, a lot of strange changes were made.

Yeah every emote is saved as a PNG, I don't really know why this is the case and I should probably fix it in the future. I don't properly read the mime type in this I just count the frames and if the framecount 1 I set the type to png and if more than 1 frame I set it to gif. Taking a look at the chat render code it looks like it either expects it to be in png or gif, so a jpeg would probably throw it off. In the end it's all decoded by SkiaSkarp so the extension doesn't matter too much.

Instead of passing the actual mime type if you change it just [on framecount](https://github.com/lay295/TwitchDownloader/blob/3fb6e12a35c2f2f48ee4b4d5756165783e728e26/TwitchDownloaderCore/TwitchHelper.cs#L96) it would probably be compatible. I don't think I've ever seen BTTV or FFZ return a jpeg only a png so I think that's why I've never seen an issue using the imageType returned from their API. So once you make the change making the image type be either png or gif (even if it's jpeg) I'll merge the PR.

I want to refactor the emote cache and render system. One day :'(

**Comment by IS2511** [comment]
My friend tested it with opaque background on an actual stream (with just this changes) and it worked afaik.
7tv also returns webp btw.

I think it's probably fine like this? It should work because it's plugged into the same `foreach (ThirdPartyEmoteData emoteData in embededEmotes.thirdParty)`. Not like I added my own loop for adding it to `returnList` or `alreadyAdded`.

The type is not important anyway? Because the `codec` is created from data only as I understand. (in the `foreach` mentioned before)

**Comment by lay295** [comment]
Oh yeah my mistake I was looking at [this line](https://github.com/lay295/TwitchDownloader/blob/afcfefa23ee52610ae10ca6c7ba6f45e4b04ef80/TwitchDownloaderCore/ChatRenderer.cs#L729) but that's just for the first party emotes so shouldn't effect the third party emotes. For third party emotes looks like anything that's [not a gif](https://github.com/lay295/TwitchDownloader/blob/afcfefa23ee52610ae10ca6c7ba6f45e4b04ef80/TwitchDownloaderCore/ChatRenderer.cs#L605) will be a static image.

**Pull request merged**
